version: '3.8'

services:
  backend:
    build:
      context: ./backend/auth
    container_name: Komail-backend
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://postgres:meptics@db:5432/dockerTestDb
    volumes:
      - ./backend/auth:/app
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: meptics
      POSTGRES_DB: dockerTestDb
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
