
services:
  backend:
    build:
      context: ./backend/auth
    container_name: Komail-backend
    ports:
      - "4000:4000"     
    environment:
      - NODE_ENV=development
    volumes:
      - ./backend/auth:/app
